FROM golang:1.7
RUN apt-get update \
    && apt-get install pkg-config libzmq-dev -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ADD . /go/src/github.com/thraxil/windsock
WORKDIR /go/src/github.com/thraxil/windsock
RUN go build windsock.go
ENV BROKER_EXPVAR_PORT 8081
EXPOSE 5555 5556 8081
CMD ["/go/src/github.com/thraxil/windsock/broker", "-config=/go/src/github.com/thraxil/windsock/broker.json"]
