FROM golang:1.7
RUN apt-get update \
    && apt-get install pkg-config libzmq-dev -y \
    && go get github.com/pebbe/zmq2 \
    && go get golang.org/x/net/websocket \
    && go get -u github.com/Sirupsen/logrus \
    && go get -u github.com/kelseyhightower/envconfig \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ADD . /go/src/github.com/thraxil/windsock
WORKDIR /go/src/github.com/thraxil/windsock
RUN go build windsock.go
EXPOSE 5050
CMD ["/go/src/github.com/thraxil/windsock/windsock", "-config=/go/src/github.com/thraxil/windsock/windsock-docker.json"]
